# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2153e8d7099362d1a1d49a6cc453e7882c68f6ca6f4b006250aa9cdd7efb4548db433624a7e7686789a02edb5470b205ea06fe5762cd4425653d20fed29d211b

test:
  secret_key_base: 102d1488c3a4424bbf83afbbf1a3efb49699ac57b24f2b760310ec33184ee98632b9f447da2822c6697a89452ca0ffcd00f49eb0a22630e398a7e6b54949223e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
